apiVersion: v1
kind: ReplicationController
metadata:
  name: puma-controller
spec:
  replicas: 3
  selector: 
    sticker: puma
  template:
    metadata:
      name: nginx-pod
      namespace: default
      labels:
        sticker: puma
        env: dev
    spec:
      containers:
        - name: nginx1-container
          image: nginx
          ports:
            - containerPort: 80


