apiVersion: v1
kind: Secret
metadata:
  name: dbsecrets
type: Opaque
data:
  CONNECTION_STRING: RHJpdmVyPXtPREJDIERyaXZlciAxNyBmb3IgU1FMIFNlcnZlcn07U2VydmVyPXRjcDpiYWNrZW5kZGIxLmRhdGFiYXNlLndpbmRvd3MubmV0LDE0MzM7RGF0YWJhc2U9dG9kb2FwcGRiO1VpZD1iYWRhbGFkbWluO1B3ZD1hZG1pbkAxMjM0NTY7RW5jcnlwdD15ZXM7VHJ1c3RTZXJ2ZXJDZXJ0aWZpY2F0ZT1ubztDb25uZWN0aW9uIFRpbWVvdXQ9MzA7
